### ISSUE TITLE
中止生成按钮会同时触发发送聊天按钮

### ISSUE THREAD

**Issue by Moyv-Wang** [liaosunny123/Sorux-GPT-Panel#1]
如果在生成时想要停止生成，并且此时你的编辑栏里有内容，点击停止生成会把编辑栏的内容发送出去。
![image](https://github.com/user-attachments/assets/5ed80810-b823-4a90-8cfd-ea363bac0222)

**Comment by liaosunny123** [comment]
这是 ChatGPT 官网的 bug，因此不予以修复
